### ISSUE TITLE
keywords for harvests

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-schemas#139]
I think there are no keywords at all for arXiv harvest.
All keywords I found are for user-submissions, e.g.
https://labs.inspirehep.net/holdingpen/list/?page=1&size=10&q=metadata.keywords.value:model

FYI:
If we have the fulltext (e.g. arXiv) we run
python bibclassify_cli.py -s -n 35 -k HEPontCore.rdf  fulltext.pdf

If we have only metadata (e.g. for journals) we run
python bibclassify_cli.py -s -n 10 -k HEPontCore.rdf  title_abstract_keywords.txt

**Comment by michamos** [comment]
Closing, as it is not related to the schemas and I answered by email.
