### ISSUE TITLE
Are TeXkeys really in 999C5k?

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-schemas#146]
Schema says (https://github.com/inspirehep/inspire-schemas/blob/1db9777634844724c522728521ab1f876b25ca8e/inspire_schemas/records/elements/reference.yml#L203) that `999C5k` contains TeXkeys, but a search on legacy disproves this: https://inspirehep.net/search?p=999C5k%3A**.

Is this actually a new thing that is going to happen with your improvements to `refextract` that you made, @michamos ?

**Comment by michamos** [comment]
Yes, on legacy, `refextract` doesn't know how to extract texkeys. This is a new feature that was introduced in inspirehep/refextract#18 and should start running when it is released and properly integrated in the labs workflows. I reserved a MARC field for it to send the texkeys back, so there is nothing there yet.
If you need an example for tests, you can pick a linked citation and add its texkey by hand (but note that texkeys are not necessarily in Inspire format, they can be whatever the authors have used in the LaTeX as citation key).

**Comment by jacquerie** [comment]
Ok, thanks :+1:
