### ISSUE TITLE
Copyright.material is not really populated

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-schemas#155]
When populating it, it's actually overriding the 'url' field:

```python
In [2]: from inspire_schemas.builders import LiteratureBuilder

In [3]: lb = LiteratureBuilder(source='mama', )

In [4]: lb
Out[4]: LiteratureBuilder(source="mama", record={})

In [5]: lb.add_copyright(material='i\'m not a url')

In [6]: lb
Out[6]: LiteratureBuilder(source="mama", record={'copyright': [{'url': "i'm not a url"}]})
```

**Comment by spirosdelviniotis** [comment]
Investigated this issue and realized that the field `copyright.year` is not supported.
From  [inspire-schemas/builder](https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/builders.py#L643-L668):

```python
def add_copyright(
        self,
        material=None,
        holder=None,
        statement=None,
        url=None
):
```
So, @david-caro should we support it?

**Comment by david-caro** [comment]
Yep, we should, another pr would be nice (one is a bugfix, the other a feature I guess).

**Comment by spirosdelviniotis** [comment]
Perfect! :+1:
