### ISSUE TITLE
experiments: institution -> institutions

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-schemas#167]
An Experiment record can have multiple associated institutions. For example: https://inspirehep.net/record/1228417/export/xme

The schema currently only allows for one: https://github.com/inspirehep/inspire-schemas/blob/006537d31a1267959ac7003805aecdb04359434a/inspire_schemas/records/experiments.yml#L249-L268.

So `institution` must be changed to to an array called `institutions` in order to accomodate them.

**Comment by michamos** [comment]
could you produce a list of all records having repeated institutions? they need to be cleaned up as we are restricting their use.
