### ISSUE TITLE
conferences: short_description is not a sourced value

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-schemas#174]
Currently `short_description` is a sourced value: https://github.com/inspirehep/inspire-schemas/blob/0bc9bc19fe2f24e721f1abfcba04547acd0e0537/inspire_schemas/records/conferences.yml#L201-L202. But it shouldn't be, because `520__9` contains no sources: https://inspirehep.net/search?cc=Conferences&p=520__9%3A**&wl=0.

In fact, it should become like `description` in Experiments: https://github.com/inspirehep/inspire-schemas/blob/0bc9bc19fe2f24e721f1abfcba04547acd0e0537/inspire_schemas/records/experiments.yml#L174-L180.

CC: @michamos

**Comment by michamos** [comment]
There is no source on legacy, but that doesn't mean there should be no source in the future.
