### ISSUE TITLE
setup.py tries to import pyyaml before installing setup_requires

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-schemas#185]
`pyyaml` is needed in `setup.py` in order to generate JSON schemas from the YAML source, but that step runs before the call to `setup()` in order for the JSON to be generated when doing an `sdist`.
This fails if `pyyaml` is not installed yet, as happens when not installing the `requirements-build.txt`.

**Comment by david-caro** [comment]
I'm not sure what to do here... you want me to add a nicer explanatory error?

**Comment by michamos** [comment]
this was solved in #266.
