### ISSUE TITLE
institutions: requiring an ICN is also too strict

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-schemas#188]
Similarly to https://github.com/inspirehep/inspire-schemas/issues/183, most records don't appear to have a `110__t` from which to populate the `ICN` key: https://inspirehep.net/search?cc=Institutions&p=110__t%3A**&wl=0 returns 3573 results out of 11196.

CC: @michamos

**Comment by michamos** [comment]
Originally the idea was to go through all institutions and either a new ICN in `110__t` or put `obsolete` as a value if the institution should disappear and be replaced with its parent institution (when we have too fine-grained institutions).
This is a Herculean task that was never completed. @annetteholtkamp should decide what to do with institutions without a `110__t`.
