### ISSUE TITLE
experiments: requiring either experiment, accelerator, or collaboration is too strict

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-schemas#192]
Currently a `project_type` is required (https://github.com/inspirehep/inspire-schemas/blob/775f6f0d9cae459257166757fda27e3ed1316537/inspire_schemas/records/experiments.yml#L364-L365) which implies the presence of either an `experiment`, an `accelerator` or a `collaboration` key (https://github.com/inspirehep/inspire-schemas/blob/775f6f0d9cae459257166757fda27e3ed1316537/inspire_schemas/records/experiments.yml#L3-L11).

Unfortunately, this is too strict. For example, we have an `experiment` key if we had either a `119__c` or a `119__d`, which almost never happens (http://inspirehep.net/search?cc=Experiments&p=119__c%3A**+or+119__d%3A**), and similar considerations apply for the other two.

Note that this started happening with https://github.com/inspirehep/inspire-schemas/pull/187, as moving `legacy_name` to the top level meant that `experiment` was no longer reliably there.

CC: @michamos

**Comment by michamos** [comment]
Indeed, with `legacy_name` pulled out of `experiment`, there isn't necessarily an `experiment` field any more. However, the `project_type` should still be present and be `experiment` by default.

I will relax the constraint and amend the docs.
