### ISSUE TITLE
Add files entries in schemas

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-schemas#200]
The plots are generated by plotextract, and need the following metadata:

- format: png, jpeg, ...
- label: The name that was given to it in the pdf
- caption: A 'join' of all the captions that image has (normally only one).
- name: The name of the plot
- key:The 'key' in the record.files "property"
- material: form the enum
- source: common source element, with the info of the source of the file.

The documents will have the following metadata:

- hidden: if the document should be hidden to the general public (true|false)
- material: the usual material field, if it's preprint, etc
- url: original url of the document if any
- source: common source element, with the info of the source of the file.
- key:The 'key' in the record.files "property"
- description: what’s inside the document
- fulltext: flag, whether it's the full content of the record, as opposed to, say, a table of contents

**Comment by michamos** [comment]
@david-caro @zzacharo @ammirate  do we really want to store the format of the plot there? isn't this computed already by `invenio-files-rest`?

**Comment by michamos** [comment]
And what is the `name` of the plot for?

**Comment by StellaCh** [comment]
As far as I understand, the name was given by the user who uploaded the plot and the key is generated from the system, right @david-caro ?

**Comment by david-caro** [comment]
Yep, the `name` is the name the user gave to it, like `fig1.png`, while the `key` is what we use to uniquely identify that file (as two plots might have the same `name`, but not the same `key`).

> @david-caro @zzacharo @ammirate do we really want to store the format of the plot there? isn't this computed already by invenio-files-rest?

It's in the schema, but afaik it does not (https://labs.inspirehep.net/api/holdingpen/682187)... though I might be missing something. In any case, the idea of having the metadata we need/want for the plots and documents in a separated key allows us to decouple it from invenio-files-rest (or any other external module for that matter) and evolve it on our own, using the `.files` property as a storage backend only.
