### ISSUE TITLE
elements: urls.value should not be validated as URI

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-schemas#280]
We currently have https://github.com/inspirehep/inspire-schemas/blob/afcc205b905f31432b1110c87cc1dffad9f2fed2/inspire_schemas/records/elements/url.yml#L10-L14 but this is too strict, since we use this field to store information like
```XML
<datafield tag="856" ind1="4" ind2=" ">
  <subfield code="u">@particleist</subfield>
  <subfield code="y">TWITTER</subfield>
</datafield>
```
which would become
```JSON
{
    "urls": [
        {
            "description": "TWITTER",
            "value": "@particleist"
        }
    ]
}
```
but `@particleist` isn't a URI.

**Comment by jacquerie** [comment]
Thing is, it makes a lot of sense to validate URLs as URIs, while it makes less sense to store there what are essentially external system identifiers. So my proposal is to relax temporarily this field to unblock https://github.com/inspirehep/inspire-next/pull/2992 and https://github.com/inspirehep/inspire-next/pull/2904 ASAP, and then restrict again when we have another place in the schema to put this information.

**Comment by michamos** [comment]
Not sure I understand. The content of those fields are not URLs but external system identifiers, so they should be moved there. Note that this is already foreseen in commit e5a1ff4 (part of #182), that adds twitter and linkedin to the allowed author `ids`. In the meantime, those authors will fail migration. What's wrong with that?

**Comment by jacquerie** [comment]
> In the meantime, those authors will fail migration. What's wrong with that?

Some of the authors that fail migration are part of our demo set of records, which means we can't bump the schemas (which is happening in commit https://github.com/inspirehep/inspire-next/pull/2992/commits/2afcbb0ba54e870bf4dffadcc7dd82a2b6db3c1e of https://github.com/inspirehep/inspire-next/pull/2992), which is blocking the manual merger from being merged.

**Comment by michamos** [comment]
can't you patch the demo records then? It seems cleaner to me to do a temporary patch at the point of failure rather than here.

**Comment by jacquerie** [comment]
> can't you patch the demo records then? It seems cleaner to me to do a temporary patch at the point of failure rather than here.

:+1:

Will do like you suggest, and thanks for the weekend answer...
