### ISSUE TITLE
PDG

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-schemas#286]
@kaplun commented on [Wed Aug 24 2016](https://github.com/inspirehep/inspire-next/issues/1479)

210 RPP should be considered as a document type.

---

@kaplun commented on [Wed Aug 24 2016](https://github.com/inspirehep/inspire-next/issues/1479#issuecomment-242003205)

See also: #1215 

---

@StellaCh commented on [Wed Nov 29 2017](https://github.com/inspirehep/inspire-next/issues/1479#issuecomment-347827099)

Can you please give more details on what should be done for this and what's the use case? @kaplun

**Comment by kaplun** [comment]
https://inspirehep.net/search?ln=en&p=210%3ARPP&of=hb&action_search=Search&sf=earliestdate&so=d those records are actually special type of documents. They are Reviews of Particle Phyics and I believe according to @annetteholtkamp they deserve to be their own kind of document type (i.e. different than article and such).

@michamos ?

**Comment by michamos** [comment]
We now have a flag for this.
