### ISSUE TITLE
Orphan affiliations

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-schemas#37]
Some ~20K records:
https://inspirehep.net/search?ln=en&p=902%3A**&of=hb&action_search=Search&sf=earliestdate&so=d&wl=0

have orphan affiliations, i.e. affiliation not attached to a specific author but just available for searching.

This are stored in MARC 902__a for Literature. We should preserve this field, because currently, it's not possible to recompute the affiliation for many of the affected records due to missing PDF.

**Comment by kaplun** [comment]
cc: @michamos @annetteholtkamp

**Comment by michamos** [comment]
we now preserve this field in [`record_affiliations`](https://inspire-schemas.readthedocs.io/en/latest/schemas/records/hep.html#hep-json-properties-record-affiliations).
