### ISSUE TITLE
raw_value in authors.affiliations

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-schemas#45]
Besides the current `value`, `record` and `curated_relation` a `raw_value` field is needed to add the value automatically extracted by tools. This field will not be editable but is helpful to then populate the `value` field (which contains the canonical name that links to a record in the Institutions database)

https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/records/hep.json#L79

**Comment by kaplun** [comment]
Was implemented in c116beb804d391f432ead794cc6e741184481ccc
