### ISSUE TITLE
Merge classification_number into keywords

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-schemas#52]
`classification_number` is actually very similar to `keywords` to the point that we can simply merge them together.

Note that on display time:
PACS should be displayed in their human friendly way. PDG, should link to the PDG website.

**Comment by michamos** [comment]
will they be displayed all together? PDG is really a quality stamp, as it means the article is deemed of sufficient value to be included in the PDG, so the scheme matters in this case.

**Comment by kaplun** [comment]
What's worse is that PACS do not have an easy to display counterpart:
https://publishing.aip.org/publishing/pacs/pacs-alphabetical-index

They are not keywords, rather large sentences :-1:

**Comment by kaplun** [comment]
Re: PDG, we can introduce a visual hint to the overall record to point out that it's cited by PDG. I would almost consider it to the same level of `review` and `introductory` etc.

**Comment by michamos** [comment]
we agreed on this today with @annetteholtkamp and @ksachs, but Kirsten would like the keyword scheme to be user-visible. Maybe something for @StellaCh ?

**Comment by ksachs** [comment]
I don't want to mix the different keyword schemes in the display and make clear what is standardized and what not. 

Wrt. list of PACS: better use [ASCII2010FullPacs.pdf](https://github.com/inspirehep/inspire-schemas/files/710558/ASCII2010FullPacs.pdf). 
The aip listing has several entries for one PACS and is better suited to go from text to PACS.
Yes, you can have
11.30.Er Charge conjugation, parity, time reversal, and other discrete symmetries
but usually it's less than 4-5 words and should easily display with 1 PACS per line.
There are not that many PACS on a paper. Up to Stella to decide.

**Comment by kaplun** [comment]
> Wrt. list of PACS: better use ASCII2010FullPacs.pdf.

Do you know if there is a text based version of this document? So that it's easier to parse.

**Comment by StellaCh** [comment]
I've noted it down and I'll check with the users during the interviews.

**Comment by salmele** [comment]
More on PACS at http://journals.aps.org/PACS
Note that these are no longer maintained since 2010 nor they will
Relevance and granularity will therefore necessarily fade away with time

**Comment by ksachs** [comment]
not with description. The 2008 txt version I have is numbers only
[ASCII2008FullPacs.txt](https://github.com/inspirehep/inspire-schemas/files/710675/ASCII2008FullPacs.txt)
Be aware that there are old PACS not included in that list. And there are **many** typos.
If you resolve to text, keep the plain number if it doesn't resolve.

**Comment by kaplun** [comment]
@salmele yup, we are aware, but since there is not yet an alternative vocabulary, there are apparently still quite some journals today actively providing PACS with their publications, so it's still worth considering them.

**Comment by fschwenn** [comment]
Once I generated a list "PACS|text" made of the PACS lists of 2010, 2008, 2006, 2003, 1998, 1996, 1995, and 1985. 
/afs/desy.de/user/l/library/lists/pacslist.txt 

-- 
Florian Schwennsen 
Deutsches Elektronen-Synchrotron DESY 
Building 01 Room O1.446 
phone: +49-40-8998-6190

**Comment by ksachs** [comment]
[pacslist.txt](https://github.com/inspirehep/inspire-schemas/files/711462/pacslist.txt)
here it is. A computer-friendly |-separated list.

**Comment by kaplun** [comment]
Lovely!
