### ISSUE TITLE
Finalize literature mini-schema

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-schemas#58]
Before deployment of Inspire 3 to labs, we need to finalize the part of the schema that is used in the harvesters that are currently on labs, namely user literature suggestions and non-CORE arXiv harvesting.

The concerned keys are:

## arXiv harvesting
```
{'abstracts', 'preprint_date', 'collections', 'external_system_numbers', 'license', 'report_numbers', 'collaborations', 'titles', 'arxiv_eprints', 'public_notes', 'acquisition_source', 'publication_info', 'copyright', 'authors', 'dois', 'page_nr', 'imprints'}
```

## Literature suggestion
```
{'external_system_numbers', 'accelerator_experiments', 'arxiv_eprints', 'collaboration', 'publication_info', 'acquisition_source', 'license', 'report_numbers', 'public_notes', 'imprints', 'abstracts', 'thesis', 'titles', 'languages', 'thesis_supervisors', 'field_categories', 'dois', 'urls', 'collections', 'title_translations', 'hidden_notes', 'authors'}
```

## Added by workflow
```
{'core', 'citeable', 'published'}
````

## Union, to go through
- [x] abstracts
- [x] accelerator_experiments
- [x] acquisition_source
- [x] arxiv_eprints
- [x] authors
- [x] citeable
- [x] collaboration
- [x] collaborations
- [x] collections
- [x] copyright
- [x] core
- [x] dois
- [x] external_system_numbers
- [x] field_categories
- [x] hidden_notes
- [x] imprints
- [x] languages
- [x] license
- [x] page_nr
- [x] preprint_date
- [x] public_notes
- [x] publication_info
- [x] published
- [x] report_numbers
- [x] thesis
- [x] thesis_supervisors
- [x] title_translations
- [x] titles
- [x] urls

**Comment by kaplun** [comment]
Closed by #68
