### ISSUE TITLE
Move from inspire-next repo jsonschema validity test

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-schemas#62]
As pointed out by @jacquerie, the test that ensures that our schemas are jsonschema compliant is sitting on:
https://github.com/inspirehep/inspire-next/blob/a6c641e860a9e7c357e30af5733edef9546afb76/tests/unit/records/test_records_jsonschemas.py

This should be moved to this repo, so that we don't commit invalid schemas.

**Comment by kaplun** [comment]
@jacquerie is this something you can look into? It would help ensuring we don't send PRs with typos or other things. @david-caro thinks validation of schema itself is implicitly done as soon as the schema is used to validate a record.

**Comment by jacquerie** [comment]
> @david-caro thinks validation of schema itself is implicitly done as soon as the schema is used to validate a record.

He's right:
```python
>>> from jsonschema import validate
>>> schema = {'title': 0}  # Invalid, because title has type string in the meta schema
>>> validate('foo', schema)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jacquerie/.virtualenvs/inspire/lib/python2.7/site-packages/jsonschema/validators.py", line 477, in validate
    cls.check_schema(schema)
  File "/Users/jacquerie/.virtualenvs/inspire/lib/python2.7/site-packages/jsonschema/validators.py", line 76, in check_schema
    raise SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: 0 is not of type u'string'

Failed validating u'type' in schema[u'properties'][u'title']:
    {u'type': u'string'}

On instance[u'title']:
    0
```
In fact: https://github.com/Julian/jsonschema/blob/ee2de6d0e0b6fed6f580cf2d744fb2790fe06a54/jsonschema/validators.py#L496-L501

**Comment by kaplun** [comment]
Then it's not necessary to add any further test.
