### ISSUE TITLE
Page numbers

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-schemas#63]
To be renamed `page_number` or `number_of_pages`?
To be enforced to be a simple `int`.

**Comment by michamos** [comment]
`pages_number` ?

**Comment by annetteholtkamp** [comment]
number_pages?

- Annette

**Comment by david-caro** [comment]
`number_pages_number`? 🤡

**Comment by kaplun** [comment]
I'd go for `number_of_pages` which nicely read in English :dancer: I love bike shedding.

**Comment by michamos** [comment]
OK, I'll take it
