### ISSUE TITLE
Generate documentation based on JSONSchema

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-schemas#73]
The documentation should have an explicit chapter that is automatically generated after the JSONSchema.

Please feel free to suggest on best practice and how this should looke like.

The aim of this project is to allow anybody to discover which fields exist and how to use them, and their structure, without having to open the JSON.

**Comment by kaplun** [comment]
@ammirate this is what we disussed IRL

**Comment by kaplun** [comment]
@david-caro might give you some hints since he has created this module.

Tools to use are: 
* sphinx: http://www.sphinx-doc.org/en/stable/
* jsonschema: https://spacetelescope.github.io/understanding-json-schema/

**Comment by michamos** [comment]
For the documentation, it would be nice if we could have some kind of lightweight format (e.g. Markdown or reStructuredText) as well as some support for links to other parts of the schema in the `description`s.

**Comment by david-caro** [comment]
Sorry for the noise, just creating the correct flags
